name: 'Deploy lambda'

inputs:
  lambda-directory:
    required: true
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
      working-directory: ${{ inputs.lambda-directory }}
    - run: npm run build
      shell: bash
      working-directory: ${{ inputs.lambda-directory }}
    - run: cp -r node_modules ./dist
      shell: bash
      working-directory: ${{ inputs.lambda-directory }}
    - run: cp package*.json ./dist
      shell: bash
      working-directory: ${{ inputs.lambda-directory }}
