name: 'Deploy lambda'

inputs:
  lambda-directory:
    required: true
runs:
  using: "composite"
  defaults:
    - shell: bash
  steps:
    - run: cp package*.json ./build
      working-directory: ${{ inputs.lambda-directory }}
    - run: npm run build
      working-directory: ${{ inputs.lambda-directory }}
    - run: npm ci --production --prefix ./build
      working-directory: ${{ inputs.lambda-directory }}