name: 'Deploy lambda'

inputs:
  lambda-directory:
    required: true
runs:
  using: "composite"
  steps:
    - run: npm ci --production
      shell: bash
      working-directory: ${{ inputs.lambda-directory }}
    - run: npm run build
      shell: bash
      working-directory: ${{ inputs.lambda-directory }}
    - run: cp node_modules ./build
      shell: bash
      working-directory: ${{ inputs.lambda-directory }}