name: 'Deploy lambda'
shell: "bash"
inputs:
  lambda-directory:
    required: true
runs:
  using: "composite"
  steps:
    - run: cp package*.json ./build
      working-directory: ${{ inputs.lambda-directory }}
    - run: npm run build
      working-directory: ${{ inputs.lambda-directory }}
    - run: npm ci --production --prefix ./build
      working-directory: ${{ inputs.lambda-directory }}