name: Deploy App
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: ./.github/actions/publish_lambda_action
        with:
          lambda-directory: ./lambdas/account
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        working-directory: ./terraform
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: ./terraform
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
