name: Deploy App

on: [push]

env:
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.TF_VAR_AWS_ACCESS_KEY_ID }}
  TF_VAR_AWS_ACCESS_KEY_SECRET: ${{ secrets.TF_VAR_AWS_ACCESS_KEY_SECRET }}
  TF_VAR_AWS_REGION: ${{ secrets.TF_VAR_AWS_REGION }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: ./.github/actions/publish_lambda_action
        with:
          lambda-directory: ./lambdas/account
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        working-directory: ./terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        id: validate
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        id: plan
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        id: apply
        run: terraform apply -auto-approve
